---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-setup
type: Opaque
data:
  # username: base64_encoded_string_here echo -n "sdgrrr" | base64
  # password: base64_encoded_string_here echo -n "dfdfdfd"| base64 --decode
  username: "c2ltcGxlX3VzZXJuYW1lCg==" #simple_username
  password: "c2ltcGxlX3Bhc3N3b3JkCg==" #simple_password
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-setup
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-setup
              key: password
...
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
...