---
apiVersion: v1
kind: Secret
metadata:
  name: mongoexpess-setup
type: Opaque
data:
  # username: base64_encoded_string_here echo -n "sdgrrr" | base64
  # password: base64_encoded_string_here echo -n "dfdfdfd"| base64 --decode
  me_username: "c2ltcGxlX3VzZXJuYW1lCg==" #simple_username
  me_password: "c2ltcGxlX3Bhc3N3b3JkCg==" #simple_password
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  # property-like keys; each key maps to a simple value
  database_url: mongodb-service # name of the MongoDB service
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongoexpess-setup
              key: me_username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongoexpess-setup
              key: me_password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        # - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        #   value: admin
        # - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        #   value: "Password@12345"
        # - name: ME_CONFIG_MONGODB_SERVER
        #   value: mongodb-service
---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer # Makes service external
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000 # Choose range from 30000:32767
...